name: Run Kitespot Agent Daily

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Call Kitespot Agent API
        run: |
          curl -X GET "${{ secrets.AGENT_API_URL }}/agent/run-kitespot-agent" -H "x-api-key: ${{ secrets.AGENT_API_KEY }}"